# Exported from Render on 2026-04-03T17:38:38Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: Banking_Fd
      runtime: python
      repo: https://github.com/rgtech2025/Banking_Fd
      plan: free
      envVars:
      - key: PYTHON_VERSION
        sync: false
      region: oregon
      buildCommand: pip install -r req.txt
      startCommand: python manage.py migrate && python manage.py collectstatic --noinput
        && gunicorn proj_fd.wsgi:application
      autoDeployTrigger: commit
      previews:
        generation: automatic
