# Generated by Django 4.1.7 on 2023-03-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainModel',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='name', max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=30, null=True)),
                ('password', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='media/user/')),
            ],
        ),
    ]
