# Generated by Django 4.1.7 on 2023-03-21 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_mainmodel_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainModel',
            new_name='userModel',
        ),
    ]
