# Generated by Django 4.1.7 on 2023-03-21 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_mainmodel_usermodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermodel',
            table='User Details',
        ),
    ]
