# Generated by Django 4.1.7 on 2023-03-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_usermodel_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userModel',
        ),
    ]
