# Generated by Django 4.2 on 2026-03-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datasetModel',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('dataset', models.FileField(upload_to='media/dataset/')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('xgb_accuracy', models.FloatField(null=True)),
                ('xgb_precision', models.FloatField(null=True)),
                ('xgb_recall', models.FloatField(null=True)),
                ('xgb_f1_score', models.FloatField(null=True)),
                ('cat_accuracy', models.FloatField(null=True)),
                ('cat_precision', models.FloatField(null=True)),
                ('cat_recall', models.FloatField(null=True)),
                ('cat_f1_score', models.FloatField(null=True)),
                ('lr_accuracy', models.FloatField(null=True)),
                ('lr_precision', models.FloatField(null=True)),
                ('lr_recall', models.FloatField(null=True)),
                ('lr_f1_score', models.FloatField(null=True)),
                ('lr_algo', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'Upload Dataset',
            },
        ),
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('predict_id', models.AutoField(primary_key=True, serialize=False)),
                ('step', models.IntegerField(default=1)),
                ('type', models.CharField(max_length=50)),
                ('amount', models.FloatField(null=True)),
                ('oldbalanceOrg', models.FloatField(null=True)),
                ('newbalanceOrig', models.FloatField(null=True)),
                ('oldbalanceDest', models.FloatField(null=True)),
                ('newbalanceDest', models.FloatField(null=True)),
                ('balance_diff_org', models.FloatField(blank=True, null=True)),
                ('balance_diff_dest', models.FloatField(blank=True, null=True)),
                ('zero_balance_flag', models.IntegerField(blank=True, null=True)),
                ('fraud_probability', models.FloatField(blank=True, null=True)),
                ('result', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'predict_form_data',
                'ordering': ['-created_at'],
            },
        ),
    ]
