# Generated by Django 4.2 on 2026-03-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='name', max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('user_status', models.CharField(default='pending', max_length=10)),
                ('address', models.CharField(max_length=1000, null=True)),
                ('password', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='media/user/')),
            ],
            options={
                'db_table': 'User_Details',
                'ordering': ['-user_id'],
            },
        ),
    ]
